// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egoyeoumkarmhllftpkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnb3llb3Vta2FybWhsbGZ0cGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2NDU0MzYsImV4cCI6MjA1NTIyMTQzNn0.gef6_KVCv7rShsaqOuhrhLQZ-omubd5FsR6vU1n1Yro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);